# -*- coding: utf-8 -*-
"""料理・食べもの ジャンルの語彙（日本語ラベル → 英語プロンプト断片）。"""

TITLE = "料理・食べもの"
ICON = "🍲"
EXAMPLE = "土鍋の湯気、真上から撮った鍋もの"
PORT = 8514

# (日本語, イラスト用タグ, 写実用の語)。3つめが None ならイラスト用をそのまま使う。
VOCAB = {
"主役": [
    ("刺身の盛り合わせ", "sashimi, plate, food focus, no humans",
     "an assortment of sliced raw fish arranged on a plate"),
    ("焼き魚", "grilled fish, food focus, no humans",
     "a whole grilled fish with crisp blistered skin"),
    ("鍋もの", "hot pot, steam, food focus, no humans",
     "a simmering hot pot of vegetables, tofu and fish"),
    ("おでん", "oden, food focus, no humans",
     "oden simmering in a pale dashi broth"),
    ("天ぷら", "tempura, food focus, no humans",
     "freshly fried tempura resting on paper"),
    ("冷奴", "tofu, food focus, no humans",
     "chilled tofu topped with grated ginger and scallion"),
    ("漬物", "pickled vegetables, food focus, no humans",
     "an assortment of japanese pickles in small dishes"),
    ("炊きたてのご飯", "rice, rice bowl, steam, no humans",
     "a bowl of freshly steamed white rice"),
    ("味噌汁", "miso soup, bowl, steam, no humans",
     "steam rising from a bowl of miso soup"),
    ("寿司", "sushi, food focus, no humans",
     "pieces of nigiri sushi lined up on a wooden board"),
    ("焼き鳥", "yakitori, skewer, food focus, no humans",
     "grilled chicken skewers over glowing charcoal"),
    ("和菓子", "wagashi, japanese sweets, food focus, no humans",
     "delicate seasonal japanese sweets"),
    ("酒と肴", "sake, food, still life, no humans",
     "a flask of sake beside a small dish of appetizers"),
    ("洋食の一皿", "food focus, plate, no humans, western food",
     "a carefully plated dish in a modern restaurant style"),
    ("盛りつける手", "hands, food, plate, food focus",
     "a pair of hands plating a dish, face out of frame"),
    ("包丁を持つ手", "hands, knife, cutting board, food",
     "hands slicing an ingredient on a cutting board"),
],
"器・盛り付け": [
    ("白磁の皿", "white porcelain plate", "a plain white porcelain plate"),
    ("粉引の陶器", "rustic pottery, matte glaze", "rustic matte-glazed pottery"),
    ("緑釉の皿", "green glazed ceramic dish", "a green-glazed ceramic dish"),
    ("黒い漆椀", "black bowl, lacquer, glossy", "a glossy black lacquered bowl"),
    ("木のまな板", "cutting board, wooden board", "a worn wooden cutting board"),
    ("竹ざる", "bamboo basket, tray", "a woven bamboo tray"),
    ("土鍋", "clay pot, donabe", "a heavy earthenware donabe pot"),
    ("鉄の鍋", "cast iron pan", "a blackened cast iron pan"),
    ("徳利と猪口", "sake bottle, sake cup", "a ceramic sake flask and small cup"),
    ("ガラスの酒器", "glass, transparent, condensation",
     "a chilled glass sake vessel beaded with condensation"),
    ("重箱", "lacquered box, bento", "a tiered lacquered box"),
    ("薬味を添える", "garnish, green onion, ginger",
     "a small garnish of grated ginger and scallion"),
    ("余白を広くとる", "simple background, minimal",
     "generous empty space around the food"),
    ("山盛り", "large serving, piled high", "a generous portion piled high"),
],
"光": [
    ("窓からの自然光", "window light, soft light", "soft daylight from a side window"),
    ("朝の斜光", "morning light, warm sunbeam", "warm morning light slanting across the table"),
    ("逆光で湯気が光る", "backlighting, steam, glowing",
     "backlight catching the rising steam"),
    ("曇りの柔らかい光", "overcast, soft diffused light", "soft diffused light on an overcast day"),
    ("提灯の灯り", "paper lantern, warm glow", "the warm glow of paper lanterns"),
    ("蝋燭", "candle, candlelight", "flickering candlelight"),
    ("炭火の赤い照り", "fire, red glow, embers", "the red glow of charcoal embers"),
    ("真上からの一灯", "single light source, overhead light",
     "a single light directly overhead"),
    ("暗がりに一筋の光", "dark, light rays, spotlight",
     "a single shaft of light in a dark room"),
    ("夕方の橙", "sunset, orange light", "warm orange light at dusk"),
    ("冷たい青い光", "cool blue lighting", "cool blue-toned light"),
    ("影をやわらげる", "soft shadows, even lighting", "shadows softened with a reflector"),
    ("ネオンの反射", "neon lights, reflection", "neon light reflecting off wet surfaces"),
],
"構図・角度": [
    ("真上から", "from above, directly overhead", "shot straight down from directly above"),
    ("斜め45度", "three-quarter view", "shot from a forty-five degree angle"),
    ("真横から", "from side, eye level", "shot level with the table from the side"),
    ("寄りのマクロ", "close-up, macro", "an extreme close-up of the surface"),
    ("引きの卓上", "wide shot, table", "a wide shot of the whole table setting"),
    ("浅い被写界深度", "depth of field, blurry background",
     "shallow depth of field, background falling away"),
    ("箸で持ち上げる", "chopsticks, holding food",
     "a piece lifted into the air with chopsticks"),
    ("断面を見せる", "cross-section, cut in half", "cut open to show the cross-section"),
    ("手前をぼかす", "blurry foreground", "something blurred in the foreground"),
    ("左右対称に置く", "symmetrical composition", "a symmetrical arrangement"),
    ("一列に並べる", "lined up, row", "arranged in a single neat row"),
    ("縦位置", "portrait orientation", "a vertical portrait-format framing"),
    ("余白に手が入る", "hands, reaching", "a hand entering the frame from the edge"),
],
"場所": [
    ("料理屋のカウンター", "restaurant counter, wooden counter",
     "the wooden counter of a small restaurant"),
    ("居酒屋", "izakaya, lanterns, indoors", "a lively izakaya interior"),
    ("家の食卓", "dining table, home, indoors", "a family dining table at home"),
    ("板場", "kitchen, professional kitchen", "a professional kitchen"),
    ("炭火の焼き台", "grill, charcoal, fire", "a charcoal grill glowing with embers"),
    ("縁側", "engawa, wooden veranda, garden", "a wooden veranda facing a garden"),
    ("座敷", "tatami, japanese room, low table", "a tatami room with a low table"),
    ("屋台", "street food stall, night", "a street food stall at night"),
    ("市場", "market, stalls", "a bustling food market"),
    ("蔵の試飲室", "tasting room, bottles lined up",
     "a sake brewery tasting room lined with bottles"),
    ("庭先", "garden, outdoors", "outdoors in a quiet garden"),
    ("雪の見える窓辺", "window, snow outside", "by a window with snow falling outside"),
    ("レストランの席", "restaurant, table setting", "a restaurant table set for dinner"),
    ("焚き火のそば", "campfire, outdoors, night", "beside a campfire outdoors"),
],
"背景・素材感": [
    ("古い木のテーブル", "wooden table, worn wood", "an old table of worn, scarred wood"),
    ("黒い石板", "black stone, slate", "a slab of dark slate"),
    ("麻の布", "linen cloth, fabric", "rumpled linen cloth"),
    ("和紙", "washi paper, textured paper", "textured japanese paper"),
    ("漆の黒", "black background, glossy", "a deep glossy black surface"),
    ("白い石の台", "white stone surface", "a pale white stone surface"),
    ("金属のトレー", "metal tray, stainless steel", "a brushed stainless steel tray"),
    ("畳", "tatami", "a tatami mat floor"),
    ("曇りガラス越し", "frosted glass", "seen through frosted glass"),
    ("暗い背景", "dark background", "a dark, almost black background"),
    ("明るい白背景", "white background, bright", "a clean bright white background"),
    ("錆びた鉄", "rusty metal", "rusted iron"),
    ("濡れた木", "wet wood, water drops", "wet wood beaded with water"),
],
"温度と状態": [
    ("湯気が立つ", "steam", "steam rising off the surface"),
    ("できたて熱々", "hot food, steaming", "piping hot, straight from the heat"),
    ("キンと冷えた", "cold, chilled", "ice cold, straight from the fridge"),
    ("露がつく", "condensation, water drops", "beaded with cold condensation"),
    ("照りのあるタレ", "glossy sauce, shiny", "a glossy lacquer of sauce"),
    ("香ばしい焦げ目", "charred, grill marks", "dark char marks from the grill"),
    ("揚げたて", "fried, crispy, oil", "just out of the fryer, still crackling"),
    ("溶けかけ", "melting", "slowly melting at the edges"),
    ("とろりと半熟", "runny yolk, soft egg", "a soft yolk running slowly"),
    ("切り口がみずみずしい", "juicy, fresh cut", "a fresh cut surface, glistening"),
    ("霜がついた", "frost, frozen", "lightly frosted over"),
    ("ふつふつ煮える", "boiling, bubbling", "simmering with small bubbles"),
],
"画風": [
    ("写真らしく", "realistic, photo (medium)", "a natural, unstyled photograph"),
    ("フィルム写真", "film grain, analog photo", "shot on film, visible grain"),
    ("モノクロ写真", "monochrome, greyscale", "a black and white photograph"),
    ("雑誌の料理写真", "food photography, styled", "a styled food magazine photograph"),
    ("ドキュメンタリー", "candid, documentary", "candid documentary-style photography"),
    ("シネマティック", "cinematic lighting", "a cinematic film still"),
    ("水彩", "watercolor (medium), traditional media, soft edges",
     "a watercolor painting"),
    ("墨絵", "ink painting, sumi-e, monochrome", "an ink wash painting"),
    ("アニメ調", "anime style, cel shaded", None),
    ("浮世絵風", "ukiyo-e, woodblock print", "in the style of a woodblock print"),
    ("レトロなポスター", "retro poster style, flat colors", "a retro poster illustration"),
    ("油絵", "oil painting (medium), thick brushwork", "an oil painting with thick brushwork"),
    ("図鑑の挿絵", "botanical illustration, detailed drawing",
     "a detailed field-guide illustration"),
],
"主役の動き": [
    ("ほとんど動かない", None, "almost still, only the faintest movement"),
    ("湯気が立ちのぼる", None, "steam rising and curling upward"),
    ("湯気ごしに揺らぐ", None, "the air shimmering with heat above the dish"),
    ("ふつふつ沸く", None, "the broth simmering, small bubbles breaking the surface"),
    ("泡が立ちのぼる", None, "bubbles rising and popping on the surface"),
    ("汁が注がれる", None, "hot broth being poured into the bowl"),
    ("酒が注がれる", None, "sake being poured into a small cup"),
    ("タレをかける", None, "glossy sauce being spooned over the dish"),
    ("粉をふりかける", None, "a fine powder being sprinkled over the top"),
    ("包丁で切る", None, "a knife slicing cleanly through the ingredient"),
    ("箸で持ち上げる", None, "chopsticks lifting a piece from the bowl"),
    ("具を鍋に入れる", None, "ingredients being lowered into the simmering pot"),
    ("油がはねる", None, "oil crackling and spitting in the pan"),
    ("溶けていく", None, "slowly melting and spreading"),
    ("皿を置く", None, "the plate being set down on the table"),
    ("炭が赤くなる", None, "charcoal glowing brighter, ash drifting up"),
],
}

# 主役が「人物なし」のとき、人の動作を足すと矛盾する
NO_HUMAN = (
    "刺身の盛り合わせ", "焼き魚", "鍋もの", "おでん", "天ぷら", "冷奴", "漬物",
    "炊きたてのご飯", "味噌汁", "寿司", "焼き鳥", "和菓子", "酒と肴", "洋食の一皿",
)

# 人物（手を含む）がいないときに丸ごと外すカテゴリ。このジャンルには該当なし
HUMAN_ONLY_CATS = ()

# 人物不在でも成立する動き
NO_HUMAN_MOTION = (
    "ほとんど動かない", "湯気が立ちのぼる", "湯気ごしに揺らぐ", "ふつふつ沸く",
    "泡が立ちのぼる", "汁が注がれる", "酒が注がれる", "油がはねる", "溶けていく",
    "炭が赤くなる",
)

# 常時表示するカテゴリ（残りは「もっと選ぶ」に畳む）
ALWAYS = {
    "illust": ("主役", "場所"),
    "photo": ("主役", "場所"),
    "video": ("主役", "場所", "主役の動き"),
}

# 「おまかせ」で振るときの、カテゴリごとの採用確率
ROLL_CHANCE = {
    "主役": 1.0,
    "場所": 1.0,
    "光": 0.9,
    "器・盛り付け": 0.8,
    "構図・角度": 0.7,
    "温度と状態": 0.7,
    "背景・素材感": 0.6,
    "画風": 0.5,
    "主役の動き": 1.0,
}
